### ISSUE TITLE
[AutoWeb] Description and Slogan are flipped

### ISSUE THREAD

**Issue by arbuleac** [3iterations/pyme-public-issues#1]
![image](https://user-images.githubusercontent.com/3797321/141183573-1f1b5c0e-09e6-4a98-a11f-f2dc503ec05c.png)

vs 

![image](https://user-images.githubusercontent.com/3797321/141183583-3a3c9c3e-f224-45eb-b28c-568f8a20422f.png)

**Comment by glebbencovschi** [comment]
Fixed on izzi constructor template.
 - reference id values for description and slogan were vice-versa
